#!/usr/bin/env python

import sys, os
import json

cmsswpath=os.environ.get('SRT_CMSSW_BASE_SCRAMRTDEL')+"/src/CATTools/CatAnalyzer/data/"
json_ = open(cmsswpath+"dataset.json")
dataset = json.load(json_)


#print ds
args=["--jobName","--fileList","--maxFiles","--cfg","--transferDest"]
for aa in dataset:
 isRDsl = (aa['name'].find("SingleMuon")>-1 or aa['name'].find("SingleElectron")>-1) 
 isRDdl = (aa['name'].find("DoubleEG")>-1 or aa['name'].find("MuonEG")>-1 or aa['name'].find("DoubleEG")>-1)
 isNoUseMC = (aa['name'].find("tt")>-1 or aa['name'].find("QCD")>-1)
 if not (isRDdl or isNoUseMC ): 
 
   ddd = "python create-batch "
   ddd+= args[0]+" "+aa['name']+" "
   ddd+= args[1]+" "+cmsswpath+"dataset_"+aa['name']+".txt "
   ddd+= args[2]+" 10 "
   if ( aa['name'].find("SingleMuon")>-1 or aa['name'].find("SingleElectron")>-1 ) :
     ddd+= args[3]+" ttbarSingleLeptonAnalyzer_RD_cfg.py "
   elif ( aa['name'].find("TT")>-1 ) :
     ddd+= args[3]+" ttbarSingleLeptonAnalyzer_ttbar_cfg.py "
   else :
     ddd+= args[3]+" ttbarSingleLeptonAnalyzer_MC_cfg.py "
   ddd+= args[4]+" /store/user/dygyun/Cattools/v744/"+aa['name']
   #ddd+= args[4]+" /store/user/dygyun/Cattools/Data_v742/"+aa['name']
###/xrootd/store/user/dygyun/Cattools/

   print ddd
   os.system(ddd)


