#!/usr/bin/env python

import sys, os
from urllib import urlopen
import csv

gdocbase = "https://docs.google.com/spreadsheets/d/1rWM3AlFKO8IJVaeoQkWZYWwSvicQ1QCXYSzH74QyZqE"
#csvMC = list(csv.reader(urlopen(gdocbase + "/pub?gid=694776205&single=true&output=csv").readlines()))
#csvMC = list(csv.reader(urlopen(gdocbase + "/edit#gid=512197961").readlines()))
csvMC = list(csv.reader(urlopen(gdocbase + "/edit#gid=1038794205").readlines()))
#csvMC = list(csv.reader(urlopen(gdocbase + "/pub?gid=212761185&single=true&output=csv").readlines()))

nameIdx = csvMC[0].index("Name")
titleIdx = csvMC[0].index("Title")
pathIdx = csvMC[0].index("Path")
xsecIdx = csvMC[0].index("Cross section (pb)")

ds=[]
for l in csvMC[1:]:
    if len(l) == 0 or len(l[0]) == 0: continue
    ds.append({'title':l[titleIdx],
               'name':l[nameIdx],
               'xsec':float(l[xsecIdx]),
               'path':l[pathIdx]})

#print ds
for aa in ds:
 if not (aa['name'].find("QCD")>-1 or aa['name'].find("DoubleEG")>-1 or aa['name'].find("MuonEG")>-1 or aa['name'].find("DoubleEG")>-1) :
   ddd= "python makeFileList "+aa['path']+" -o filelist/"+aa['name']+".txt"
   print ddd
   os.system(ddd)
