#!/usr/bin/env python
import sys, os

from urllib import urlopen
import csv
import json
#> catGetDatasetInfo v7-4-3
#cmsswpath=os.environ.get('SRT_CMSSW_BASE_SCRAMRTDEL')+"/src/CATTools/CatAnalyzer/data/"
cmsswpath=os.environ.get('SRT_CMSSW_BASE_SCRAMRTDEL')+"/src/CATTools/CatAnalyzer/data/dataset/"
json_ = open(cmsswpath+"dataset.json")
#json_ = open(cmsswpath+"dataset/dataset.json")
dataset = json.load(json_)

iii=0
args=["--jobName","--fileList","--maxFiles","--cfg","--transferDest","--args"]
#args=["--jobName","--fileList","--maxFiles","--cfg","--transferDest","--args","--customise customise_cff.py"]
for aa in dataset:
 skip = (aa['name'].find("JetHT")>-1 or aa['name'].find("GG")>-1 or aa['name'].find("Double")>-1 
          or aa['name'].find("ZZTo")>-1 or aa['name'].find("VBF")>-1 or aa['name'].find("Gl")>-1  
          or aa['name'].find("EG")>-1 or aa['name'].find("tt")>-1 or aa['name'].find("alpha")>-1 or aa['name'].find("TTTT")>-1 
          or aa['name'].find("mpi")>-1 or aa['name'].find("noCR")>-1 or aa['name'].find("noHadron")>-1 
          or aa['name'].find("WWT")>-1 or aa['name'].find("WW_dps")>-1 or aa['name'].find("WWZ")>-1  
          or aa['name'].find("WZTo")>-1 or aa['name'].find("WZZ")>-1 or aa['name'].find("WpWp")>-1 or aa['name'].find("HT")>-1 
          or aa['name'].find("WWW")>-1 or aa['name'].find("TTLL")>-1 or aa['name'].find("WJets_MG")>-1 
          or aa['name'].find("WgstarToLNu")>-1 or aa['name'].find("ST_TH_1L3B")>-1 or aa['name'].find("LeptonicDecay_TH")>-1 
          or aa['name'].find("WGtoLNuG")>-1 or aa['name'].find("GJets")>-1 or aa['name'].find("EMEnriched")>-1 or aa['name'].find("QCD")>-1 
          or aa['name'].find("mtop")>-1 or aa['name'].find("herwigpp")>-1 or aa['name'].find("TTG")>-1 or aa['name'].find("TTbarDMJets")>-1 
          or aa['name'].find("Photon")>-1 or aa['name'].find("ZGto2LG")>-1 or aa['name'].find("DYJets_MG")>-1  
          or aa['name'].find("DYJets_0J")>-1 or aa['name'].find("DYJets_2")>-1 or aa['name'].find("DYJets_0")>-1  
          or aa['name'].find("ZZto4L")>-1 or aa['name'].find("ZZZ")>-1 or aa['name'].find("WWTo2L2Nu_powheg")>-1  )
 isRDsl = (aa['name'].find("SingleMuon")>-1 or aa['name'].find("SingleElectron")>-1)
# isSignal = (aa['name'].find("TT")>-1) 
# isRDdl = (aa['name'].find("DoubleEG")>-1 or aa['name'].find("MuonEG")>-1 or aa['name'].find("DoubleEG")>-1)
# isNoUseMC = (aa['name'].find("tt")>-1 or aa['name'].find("QCD")>-1)
# if not skip and isDATA :
 #if not (isRDdl or isNoUseMC ):
 if not skip : 
   ddd = "create-batch "
   ddd+= args[0]+" "+aa['name']+" "
   ddd+= args[1]+" "+cmsswpath+"dataset_"+aa['name']+".txt "
   #ddd+= args[1]+" "+cmsswpath+"dataset/dataset_"+aa['name']+".txt "
   ddd+= args[2]+" 20 "
   if ( aa['name'].find("SingleMuon")>-1 or aa['name'].find("SingleElectron")>-1 ) :
     ddd+= args[3]+" topAnalyzer_RD_cfg.py "
   else :
     ddd+= args[3]+" topAnalyzer_MC_cfg.py "
   fff = "/store/user/dygyun/Cattools/Catv806_mediumId_noIsoElectron_forABCD/"+aa['name']
   ddd+= args[4]+" "+fff+" "
   #ddd+= args[6]
   
   print ddd
   os.system(ddd)
   iii=iii+1

